// PROTOTYPE — throwaway semantic data for deepep_moe_dis_dispatch (2).h.
// Question: which information hierarchy makes a 4,357-line kernel easiest to read?

window.WALKTHROUGH_DATA = {
  source: {
    name: "deepep_moe_dis_dispatch (2).h",
    language: "C++ / AscendC",
    expectedLines: 4357,
    purpose: "把本 rank 的 token 按 expert 路由，跨 rank 发送，并在目标侧整理为连续的专家输入。",
  },
  modules: [
    {
      id: "orchestrate",
      step: "00",
      name: "Process · 总调度",
      short: "按 AIV 角色并发调度发送、计数与收包",
      range: [4279, 4357],
      color: "#6d5dfc",
      kind: "control",
      tips: [
        "这是读完整文件最合适的入口：先分辨当前 AIV 属于 stage、doorbell 还是 cumsum 角色。",
        "三条角色分支最终汇合到 LocalWindowCopy，把目标侧分散数据整理成连续输出。",
      ],
      functions: ["Process"],
      edges: ["contract", "preprocess", "pack", "transport", "accounting", "format"],
    },
    {
      id: "contract",
      step: "01",
      name: "Contract · 接口与状态",
      short: "常量、SIMT helper、类接口与内存布局",
      range: [1, 722],
      color: "#657084",
      kind: "structure",
      tips: [
        "通信块固定 512B，其中 480B 是 payload，尾部区域承载 ready flag。",
        "expandIdx 保存源 rank、源 token、原 top-k slot 三元组，是从输出反查输入的关键。",
      ],
      functions: ["simt_prepare_mapping", "buildRemoteWqeDesc", "calc_rank_token_cnt", "set_gm_value"],
      edges: ["init"],
    },
    {
      id: "init",
      step: "02",
      name: "Init · 建立执行上下文",
      short: "绑定 GM/UB、tiling、rank 与共享窗口",
      range: [723, 1013],
      color: "#1e8d72",
      kind: "setup",
      tips: ["tiling 决定 AIV 分工、专家分布和窗口布局；后续分支大多由这里计算出的字段驱动。"],
      functions: ["Init", "SetTilingDataAndCal", "SetTilingData", "InitElasticInfo"],
      edges: ["preprocess"],
    },
    {
      id: "preprocess",
      step: "03",
      name: "Mask · 筛选有效 token",
      short: "复制 expertIds，应用 token/expert mask",
      range: [2255, 2479],
      color: "#e7952c",
      kind: "filter",
      tips: ["一维 token mask 与二维 expert mask 走不同计算路径，但都收敛到有效 token / expert 索引。"],
      functions: ["ExpIdsCopyAndMaskCal", "TokenActiveMaskCal", "CalValidBSCnt", "CalValidExpIdx", "ExpertActiveMaskInit", "ExpertActiveMaskCal", "MaskZeroComputeExpert", "GenerateGatherMaskTensor", "ZeroComputeExpertMaskCal"],
      edges: ["pack", "accounting"],
    },
    {
      id: "pack",
      step: "04",
      name: "Stage · token 重排与暂存",
      short: "按目标 expert 计算位置并写入 send buffer",
      range: [1014, 1512],
      color: "#d05b71",
      kind: "transform",
      tips: [
        "核心索引是 token → expert → rank；FillTriple 同步记录 rank_id、token_id、topk_id。",
        "量化模式通过模板分支编译期选择，不应把这些 if constexpr 当成运行时开销。",
      ],
      functions: ["AllToAllDispatch", "SendToMoeExpertNew", "SendToSharedExpert", "TokenToExpertInQuant", "TokenToExpert", "FillTriple", "SplitToCore", "SendToMoeExpert", "CalAndSendCnt"],
      edges: ["transport", "selfcopy"],
    },
    {
      id: "transport",
      step: "05",
      name: "URMA · 远端发送",
      short: "按 expert 建图、构造 WQE 并写入 SQ",
      range: [2480, 3891],
      color: "#1687a7",
      kind: "network",
      tips: [
        "token 先只写一次本地 staging buffer；URMA 再按 (expert, token) 建映射并生成远端 WQE。",
        "WQE 的 route → 原子预留 head → write → bitmap publish 四段式协议，保证独立 doorbell 核只提交连续就绪区间。",
      ],
      functions: ["URMASendToken", "simt_nw_mj", "get_sqs_and_cqs_xb", "get_wqe_content", "simt_write_wqe", "URMAPollCQ"],
      edges: ["format"],
    },
    {
      id: "selfcopy",
      step: "06A",
      name: "SelfCopy · 本 rank 快路",
      short: "跳过网络，直接把本地 expert token 复制到目标窗口",
      range: [3892, 4000],
      color: "#8a6c3b",
      kind: "local",
      tips: ["本 rank token 不需要 URMA；单独的快路径也让远端 WQE 数量更准确。"],
      functions: ["SelfCopyToken"],
      edges: ["format"],
    },
    {
      id: "doorbell",
      step: "06B",
      name: "Doorbell · 发布远端任务",
      short: "握手 head-ready，扫描 bitmap 并提交 SQ head",
      range: [4001, 4278],
      color: "#bf4b32",
      kind: "network",
      tips: [
        "Doorbell 与 WQE 核是双向握手：先发布 head-ready，WQE 核写完后再发布 head-record bitmap。",
        "只提交从旧 head 开始的连续 ready WQE，不能跳过 bitmap 中间的空洞。",
      ],
      functions: ["RingDoorbell"],
      edges: ["format"],
    },
    {
      id: "accounting",
      step: "07",
      name: "Count · 计数与前缀和",
      short: "聚合接收计数，计算每 expert 输出偏移",
      range: [1513, 1894],
      color: "#a95bb5",
      kind: "reduce",
      tips: [
        "通信只解决数据到达；CumSum 把每个 expert 的 token 数转换成连续输出的起始偏移。",
        "flag + busy wait 是跨核/跨 rank 可见性协议的一部分，阅读时要连同状态空间偏移一起看。",
      ],
      functions: ["CalCumSum", "CalRecvAndSetFlag", "WaitDispatch", "GetCumSum", "SetExpertTokenNums", "BufferInit", "GatherSumRecvCnt", "WaitCumSumFlag"],
      edges: ["format"],
    },
    {
      id: "format",
      step: "08",
      name: "Format · 连续化输出",
      short: "等待到达、复制并生成 expandX / expandIdx",
      range: [1895, 2254],
      color: "#3474d4",
      kind: "output",
      tips: [
        "CheckDataArriveWithFlag 先判断可消费区间，CopyInAndOut 再搬运，避免读到尚未完成的远端写。",
        "最终输出不仅有 expandX，还包括 expandIdx、expertTokenNums 与可选动态量化 scale。",
      ],
      functions: ["LocalWindowCopy", "WaitAndFormatOutput", "CheckDataArriveWithFlag", "CopyInAndOut", "SetValidExpertInfo"],
      edges: [],
    },
  ],
  glossary: [
    ["AIV", "Ascend Vector Core。不同 AIV 在 Process 中承担 stage、doorbell、cumsum 等角色。"],
    ["GM / UB", "Global Memory / Unified Buffer；GM 容量大，UB 是核内高速暂存。"],
    ["WQE / CQE", "Work Queue Element / Completion Queue Element；描述一次 URMA 工作及其完成状态。"],
    ["Doorbell", "通知设备消费已经写好的 WQE 的机制。"],
    ["expandIdx", "每个展开 token 对应的 rank_id、token_id、topk_id 三元组索引。"],
    ["CumSum", "根据每个 expert 的 token 数做前缀和，得到连续输出区间。"],
    ["dataState", "双缓冲状态位；将本轮与上一轮的窗口区域隔离。"],
    ["full mesh", "EP ranks 之间可直接互发；本文件同时处理远端与本 rank 快路径。"],
  ],
  coreSymbols: [
    { pattern: "xGMTensor_", type: "input", label: "输入 hidden states" },
    { pattern: "expertIdsGMTensor_", type: "input", label: "输入 token→expert 路由" },
    { pattern: "scalesGMTensor_", type: "input", label: "输入量化 scale" },
    { pattern: "xActiveMaskGMTensor_", type: "input", label: "输入有效 token mask" },
    { pattern: "elasticInfoGMTensor_", type: "input", label: "输入弹性拓扑信息" },
    { pattern: "validExpertIdsTensor_", type: "input", label: "筛选后的 expert 路由" },
    { pattern: "dataFlagGlobal", type: "input", label: "输入：接收窗口与 ready flag" },
    { pattern: "xOutInt32Tensor", type: "input", label: "输入：已到达 token 的整数视图" },
    { pattern: "expandXOutGM_", type: "output", label: "输出专家连续输入" },
    { pattern: "expandXOutGlobal", type: "output", label: "输出：连续专家 token 视图" },
    { pattern: "dstWinGMTensor", type: "output", label: "输出：staging / 目标窗口" },
    { pattern: "outTensor_", type: "output", label: "输出：本地通信包暂存" },
    { pattern: "dynamicScalesOutGMTensor_", type: "output", label: "输出动态量化 scale" },
    { pattern: "expandIdxGMTensor_", type: "output", label: "输出三元组反向索引" },
    { pattern: "expertTokenNumsOutGMTensor_", type: "output", label: "输出每 expert token 数" },
    { pattern: "sendCountsOutGM_", type: "output", label: "输出接收前缀计数" },
    { pattern: "sendTpCountOutGM_", type: "output", label: "输出调试时钟 / TP 计数" },
    { pattern: "AllToAllDispatch", type: "api", label: "核心：本地重排与暂存" },
    { pattern: "ExpIdsCopyAndMaskCal", type: "api", label: "核心：路由与 mask 预处理" },
    { pattern: "SendToMoeExpertNew", type: "api", label: "核心：token staging" },
    { pattern: "URMASendToken", type: "api", label: "核心：远端发送" },
    { pattern: "SelfCopyToken", type: "api", label: "核心：本 rank 快路径" },
    { pattern: "RingDoorbell", type: "api", label: "核心：发布 SQ head" },
    { pattern: "CalCumSum", type: "api", label: "核心：输出偏移计算" },
    { pattern: "LocalWindowCopy", type: "api", label: "核心：目标侧整理" },
    { pattern: "WaitAndFormatOutput", type: "api", label: "核心：轮询到达并格式化" },
    { pattern: "CheckDataArriveWithFlag", type: "api", label: "核心：检查数据块 ready flag" },
    { pattern: "CopyInAndOut", type: "api", label: "核心：写 expandX / expandIdx" },
    { pattern: "CopyScalesToOut", type: "api", label: "核心：写量化 scale 输出" },
    { pattern: "simt_prepare_mapping", type: "api", label: "核心：expert→token 映射" },
    { pattern: "buildRemoteWqeDesc", type: "api", label: "核心：构造 WQE 描述" },
    { pattern: "simt_nw_mj", type: "api", label: "核心：写 WQE / 发布 bitmap" },
    { pattern: "PipeBarrier", type: "sync", label: "流水线同步" },
    { pattern: "SyncAll", type: "sync", label: "核间同步" },
    { pattern: "while (true)", type: "loop", label: "轮询 / 消费循环" },
  ],
};
